
tasks:
  build:
    runner: python:3.11.4
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - cache/push:
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        - \C:\Users\gowth\env
    - reports/junit: test-reports/*.xml
    - reports/html: 
        dir: htmlcov
