
tasks:
  build:
    runner: python:3.11.4
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - commands:
      - python app.py

      - export PATH="$(python3 -m site --user-base)/bin:$PATH"
    - cache/push:
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        - /C:\Users\gowth\env\Lib\site-packages\flask
    - reports/junit: test-reports/*.xml
    - reports/html: 
        dir: htmlcov
