
tasks:
  build: application
    runner: razorci/python
    - commands:
      - python app.py

      - export PATH="$(python3 -m C:\Users\gowth\env\Lib\site-packages\flask"
      # generate coverage reports
      - coverage run app.py
      - coverage report && coverage html
        paths:
        - /C:\Users\gowth\env
    - reports/junit: test-reports/*.xml
    - reports/html: 
        dir: htmlcov
