tasks:
  unit-tests:
    runner: razorci/python:3.9
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - commands:
      - python test.py
      - export PATH="$(python3 -m site --user-base)/bin:$PATH"
      # generate coverage reports
      - coverage report && coverage html
    - cache/push:
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        - /C:\Users\gowth\env\Lib\site-packages\flask
    - reports/junit:
  
